#Hugo configuration
title = "dertgf"
baseURL = "https:\/\/sdfds.zcxv.rfg"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
